var hanziben =
	[
		{
			lesson: "0",
			words: [
				{ fr: "un", zh: "一", pinyin: ["yi1"] },
				{ fr: "deux", zh: "二", pinyin: ["er4"] },
				{ fr: "trois", zh: "三", pinyin: ["san1"] },
				{ fr: "quatre", zh: "四", pinyin: ["si4"] },
				{ fr: "cinq", zh: "五", pinyin: ["wu3"] },
				{ fr: "six", zh: "六", pinyin: ["liu4"] },
				{ fr: "sept", zh: "七", pinyin: ["qi1"] },
				{ fr: "huit", zh: "八", pinyin: ["ba1"] },
				{ fr: "neuf", zh: "九", pinyin: ["jiu3"] },
				{ fr: "dix", zh: "十", pinyin: ["shi2"] },
				{ fr: "homme", zh: "人", pinyin: ["ren2"] },
				/*{ fr: "grand", pinyin: ["da4"] },*/
				/*{ fr: "bouche", pinyin: ["kou3"] },*/
				/*{ fr: "milieu", pinyin: ["zhong1"] },*/
				/*{ fr: "petit", pinyin: ["xiao3"] },*/
				{ fr: "dessus", zh: "上", pinyin: ["shang4"] },
				{ fr: "dessous", zh: "下", pinyin: ["xia4"] },
				/*{ fr: "pays", pinyin: ["guo2"] },*/
				{ fr: "Chine", zh: "中国", pinyin: ["Zhong1", "guo2"] },
				{ fr: "étudier, apprendre", zh: "学习", pinyin: ["xue2", "xi2"] },
				/*{ fr: "langage (1)", pinyin: ["yu3"] },*/
				/*{ fr: "langage (2)", pinyin: ["wen2"] },*/
				{ fr: "écrire", zh: "写", pinyin: ["xie3"] },
				/*{ fr: "caractère", pinyin: ["zi4"] },*/
				/*{ fr: "langue chinoise (1)", pinyin: ["Han4", "yu3"] },*/
				{ fr: "langue chinoise", zh: "中文", pinyin: ["Zhong1", "wen2"] },
				{ fr: "caractère chinois", zh: "汉字", pinyin: ["Han4", "zi4"] },
				/*{ fr: "femme", pinyin: ["nv3"] },*/
				/*{ fr: "fils, enfant", pinyin: ["zi3"] },*/
				{ fr: "bien, bon", zh: "好", pinyin: ["hao3"] },
				{ fr: "eau", zh: "水", pinyin: ["shui3"] },
				{ fr: "porte", zh: "门", pinyin: ["men2"] },
				{ fr: "roi", zh: "王", pinyin: ["wang2"] },
				/*{ fr: "femme, fille", pinyin: ["nv3", "zi3"] },*/
				/*{ fr: "entrée", pinyin: ["men2", "kou3"] },*/
				/*{ fr: "roi (2)", pinyin: ["guo2", "wang2"] },*/
				{ fr: "soleil", zh: "日", pinyin: ["ri4"] },
				{ fr: "lune", zh: "月", pinyin: ["yue4"] },
				{ fr: "bois", zh: "木", pinyin: ["mu4"] },
				{ fr: "cheval", zh: "马", pinyin: ["ma3"] },
				{ fr: "champ", zh: "田", pinyin: ["tian2"] },
				{ fr: "ciel", zh: "天", pinyin: ["tian1"] },
				{ fr: "lumineux", zh: "明亮", pinyin: ["ming2"] },
				{ fr: "forêt", zh: "林", pinyin: ["lin2"] },
				{ fr: "mère", zh: "妈妈", pinyin: ["ma1", "ma"] },
				{ fr: "rivière", zh: "河", pinyin: ["he2"] }						
			]
		},
		{
			lesson: "1",
			words: [
				{ fr: "vous", zh: "您", pinyin: ["nin2"] },
				/*{ fr: "honorable", pinyin: ["gui4"] },*/
				{ fr: "nom, s'appeller", zh: "姓", pinyin: ["xing4"] },
				/*{ fr: "je, me, moi", zh: "我", pinyin: ["wo3"] },*/
				{ fr: "<i>particule<br/>interrogative 1</i>", zh: "呢", pinyin: ["ne"] },
				{ fr: "être", zh: "是", pinyin: ["shi4"] },
				{ fr: "<i>particule<br/>interrogative 2</i>", zh: "吗", pinyin: ["ma"] },
				{ fr: "non, ne pas", zh: "不", pinyin: ["bu4"] },
				{ fr: "camarade</br>de classe", zh: "同学", pinyin: ["tong2", "xue2"] },
				{ fr: "<i>suffixe</i><br/>ou <i>pluriel</i>", zh: "们", pinyin: ["men"] },
				{ fr: "professeur", zh: "老师", pinyin: ["lao3", "shi1"] },
				{ fr: "(s')appeler,<br/>nommer", zh: "叫", pinyin: ["jiao4"] },
				{ fr: "tu, toi, te", zh: "你", pinyin: ["ni3"] },
				{ fr: "quoi, que, quel", zh: "什么", pinyin: ["shen2", "me"] },
				{ fr: "prénom", zh: "名字", pinyin: ["ming2", "zi"] },
				{ fr: "quel", zh: "哪", pinyin: ["na3"] },
				{ fr: "aussi,<br/>non plus", zh: "也", pinyin: ["ye3"] },
				{ fr: "dire,<br/>parler", zh: "说", pinyin: ["shuo1"] },
				{ fr: "langue anglaise", zh: "英语", pinyin: ["ying1", "yu3"] },
				{ fr: "ou", zh: "还是", pinyin: ["hai2", "shi4"] },
				{ fr: "langue française", zh: "法语", pinyin: ["fa3", "yu3"] },
				{ fr: "tout, tous", zh: "都", pinyin: ["dou1"] },
				{ fr: "il, lui", zh: "他", pinyin: ["ta1"] },
				{ fr: "elle", zh: "她", pinyin: ["ta1"] },
				{ fr: "seulement,<br/>uniquement", zh: "只", pinyin: ["zhi3"] }
			]
		},
		{
			lesson: "2",
			words: [
				{ fr: "connaître", zh: "认识", pinyin: ["ren4", "shi"] },
				{ fr: "très", zh: "很", pinyin: ["hen3"] },
				{ fr: "heureux, content", zh: "高兴", pinyin: ["gao1", "xing4"] },
				{ fr: "(être) dans,<br/>en, sur...", zh: "在", pinyin: ["zai4"] },
				/* { fr: "import-export", zh: "进出口", pinyin: ["jin4", "chu1", "kou3"] }, */
				{ fr: "entreprise", zh: "公司", pinyin: ["gong1", "si1"] },
				{ fr: "travailler, travail", zh: "工作", pinyin: ["gong1", "zuo4"] },
				{ fr: "université", zh: "大学", pinyin: ["da4", "xue2"] },
				/*{ fr: "département", zh: "系", pinyin: ["xi4"] },*/
				{ fr: "pouvoir", zh: "可以", pinyin: ["ke3", "yi3"] },
				{ fr: "donner, à,<br/>pour", zh: "给", pinyin: ["gei3"] },
				{ fr: "téléphoner", zh: "打电话", pinyin: ["da3", "dian4", "hua4"] },
				{ fr: "mon", zh: "我的", pinyin: ["wo3", "de"] },
				{ fr: "numéro", zh: "号码", pinyin: ["hao4", "ma3"] },
				{ fr: "envoyer,<br/>poster", zh: "发", pinyin: ["fa1"] },
				{ fr: "adresse e-mail", zh: "电子邮件", pinyin: ["dian4", "zi3", "you2", "jian4"] },
				{ fr: "ce, cet,<br/>cette", zh: "这", pinyin: ["zhe4"] },
				{ fr: "féminin", zh: "女", pinyin: ["nv3"] },
				{ fr: "ami", zh: "朋友", pinyin: ["peng2", "you"] },
				{ fr: "SVP,<br/>prier de", zh: "请", pinyin: ["qing3"] },
				{ fr: "s'asseoir", zh: "坐", pinyin: ["zuo4"] },
				{ fr: "merci", zh: "谢谢", pinyin: ["xie4", "xie"] },
				{ fr: "boire", zh: "喝", pinyin: ["he1"] },
				{ fr: "thé", zh: "茶", pinyin: ["cha2"] },
				{ fr: "où", zh: "哪儿", pinyin: ["nar3",""] },
				{ fr: "institut", zh: "学院", pinyin: ["xue2","yuan4"] },
				{ fr: "comment <i>(avis)</i>", zh: "怎么样", pinyin: ["zen3", "me", "yang4"] },
				{ fr: "joli, beau", zh: "漂亮", pinyin: ["piao4", "liang"] },
				{ fr: "aimer", zh: "喜欢", pinyin: ["xi3", "huan"] },
				{ fr: "ce, cela", zh: "那", pinyin: ["na4"] },
				{ fr: "masculin", zh: "男", pinyin: ["nan2"] },
				{ fr: "petit", zh: "小", pinyin: ["xiao3"] }
			]
		},
		{
			lesson: "3",
			words: [
				{ fr: "endroit", zh: "地方", pinyin: ["di4", "fang"] },
				{ fr: "<i>spécificatif</i>", zh: "个", pinyin: ["ge4"] },
				{ fr: "maison, famille", zh: "家", pinyin: ["jia1"] },
				{ fr: "avoir", zh: "有", pinyin: ["you3"] },
				{ fr: "combien", zh: "几", pinyin: ["ji3"] },
				{ fr: "père, papa", zh: "爸爸", pinyin: ["ba4", "ba"] },
				{ fr: "et", zh: "和", pinyin: ["he2"] },
				{ fr: "épouse", zh: "太太", pinyin: ["tai4", "tai"] },
				{ fr: "enfant", zh: "孩子", pinyin: ["hai2", "zi"] },
				{ fr: "beaucoup", zh: "多", pinyin: ["duo1"] },
				{ fr: "deux", zh: "两", pinyin: ["liang3"] },
				{ fr: "âge", zh: "岁", pinyin: ["sui4"] },
				{ fr: "aimer", zh: "爱", pinyin: ["ai4"] },
				{ fr: "particule", zh: "吧", pinyin: ["ba"] },
				{ fr: "école", zh: "学校", pinyin: ["xue2", "xiao4"] },
				{ fr: "peu", zh: "少", pinyin: ["shao3"] },
				{ fr: "étudiant", zh: "学生", pinyin: ["xue2", "sheng(1)"] },
				{ fr: "penser, vouloir<br/>faire qch.", zh: "想", pinyin: ["xiang3"] },
				{ fr: "peut-être,<br/>environ", zh: "大概", pinyin: ["da4", "gai4"] },
				{ fr: "10'000", zh: "万", pinyin: ["wan4"] },
				{ fr: "ne pas", zh: "没", pinyin: ["mei2"] },
				{ fr: "1'000", zh: "千", pinyin: ["qian1"] },
				{ fr: "aller", zh: "去", pinyin: ["qu4"] },
				/*{ fr: "branche", zh: "分", pinyin: ["fen1"] },*/
				{ fr: "boss", zh: "老板", pinyin: ["lao3", "ban3"] },
				{ fr: "laisser,<br/>permettre", zh: "让", pinyin: ["rang4"] },
				{ fr: "100", zh: "百", pinyin: ["bai3"] },
				{ fr: "parce que,<br/>car", zh: "因为", pinyin: ["yin1", "wei4"] }						
			]
		},
		{
			lesson: "4",
			words: [
				{ fr: "carte", zh: "地图", pinyin: ["di4", "tu2"] },
				{ fr: "<i>spécif.<br/>(papier)</i>", zh: "张", pinyin: ["zhang1"] },
				{ fr: "regarder", zh: "看", pinyin: ["kan4"] },
				{ fr: "d'accord", zh: "行", pinyin: ["xing4"] },
				{ fr: "vouloir", zh: "要", pinyin: ["yao4"] },
				{ fr: "faire", zh: "干", pinyin: ["gan4"] },
				{ fr: "jouer", zh: "玩儿", pinyin: ["wanr2", ""] },
				{ fr: "savoir", zh: "知道", pinyin: ["zhi1", "dao4"] },
				{ fr: "relativement", zh: "比较", pinyin: ["bi3", "jiao4"] },
				{ fr: "réellement", zh: "真", pinyin: ["zhen1"] },
				{ fr: "signification", zh: "意思", pinyin: ["yi4", "si1"] },
				{ fr: "dragon", zh: "龙", pinyin: ["long2"] },
				{ fr: "montagne", zh: "山", pinyin: ["shan1"] },
				{ fr: "dictionnaire", zh: "词典", pinyin: ["ci2", "dian3"] },
				{ fr: "<i>spécif.<br/>(livre)</i>", zh: "本", pinyin: ["ben3"] },
				{ fr: "qui", zh: "谁", pinyin: ["shui2"] },
				{ fr: "demander", zh: "问", pinyin: ["wen4"] },
				{ fr: "très", zh: "非常", pinyin: ["fei1", "chang2"] },
				{ fr: "utiliser", zh: "用", pinyin: ["yong4"] },
				{ fr: "pouvoir", zh: "能", pinyin: ["neng2"] },
				{ fr: "bien sûr", zh: "当然", pinyin: ["dang1", "ran2"] },
				{ fr: "livre", zh: "书", pinyin: ["shu1"] },
				{ fr: "stylo", zh: "笔", pinyin: ["bi3"] },
				{ fr: "<i>spécif.<br/>(stylos)</i>", zh: "支", pinyin: ["zhi1"] },
				{ fr: "salle de classe", zh: "教室", pinyin: ["jiao4", "shi4"] },
				{ fr: "leçon", zh: "课", pinyin: ["ke4"] }
			]
		},
		{
			lesson: "5",
			words: [
				{ fr: "mademoiselle", zh: "小姐", pinyin: ["xiao3", "jie3"] },
				{ fr: "savoir faire<br/>qqch", zh: "会", pinyin: ["hui4"] },
				{ fr: "un peu", zh: "一点儿", pinyin: ["yi4", "dianr3", ""] },
				{ fr: "monsieur", zh: "先生", pinyin: ["xian1", "sheng1"] },
				{ fr: "acheter", zh: "买", pinyin: ["mai3"] },
				{ fr: "chemise", zh: "衬衫", pinyin: ["chen4", "shan1"] },
				{ fr: "blanc", zh: "白", pinyin: ["bai2"] },
				{ fr: "argent", zh: "钱", pinyin: ["qian2"] },
				{ fr: "Renminbi", zh: "块", pinyin: ["kuai4"] },
				{ fr: "Yuan", zh: "元", pinyin: ["yuan2"] },
				{ fr: "<i>(passé)</i>", zh: "了", pinyin: ["le"] },
				{ fr: "cher", zh: "贵", pinyin: ["gui4"] },
				{ fr: "rouge", zh: "红", pinyin: ["hong2"] },
				{ fr: "bon marché", zh: "便宜", pinyin: ["pian2", "yi4"] },
				{ fr: "<i>spécif.<br/>(pantalons)</i>", zh: "条", pinyin: ["tiao4"] },
				{ fr: "pantalon", zh: "裤子", pinyin: ["ku4", "zi3"] },
				{ fr: "essayer", zh: "试", pinyin: ["shi4"] },
				{ fr: "venir", zh: "来", pinyin: ["lai2"] },
				{ fr: "restaurant", zh: "饭店", pinyin: ["fan4", "dian4"] },
				{ fr: "le plus", zh: "最", pinyin: ["zui4"] },
				{ fr: "manger", zh: "吃", pinyin: ["chi1"] },
				{ fr: "plat", zh: "菜", pinyin: ["cai4"] },
				{ fr: "sucre", zh: "糖", pinyin: ["tang2"] },
				{ fr: "vinaigre", zh: "醋", pinyin: ["cu4"] },
				{ fr: "poisson", zh: "鱼", pinyin: ["yu2"] },
				{ fr: "acide", zh: "酸", pinyin: ["suan"] },
				{ fr: "piquant", zh: "辣", pinyin: ["la4"] },
				{ fr: "soupe", zh: "汤", pinyin: ["tang1"] },
				{ fr: "bœuf", zh: "牛肉", pinyin: ["niu2", "rou4"] },
				{ fr: "cuire", zh: "烧", pinyin: ["shao1"] },
				{ fr: "riz", zh: "米", pinyin: ["mi3"] },
				{ fr: "ravioli chinois", zh: "水饺", pinyin: ["shui3", "jiao3"] },
				{ fr: "attendre", zh: "等", pinyin: ["deng3"] },
				{ fr: "est", zh: "东", pinyin: ["dong1"] },
				{ fr: "ouest", zh: "西", pinyin: ["xi1"] },
				{ fr: "magasin", zh: "商店", pinyin: ["shang1", "dian4"] },
				{ fr: "vendre", zh: "卖", pinyin: ["mai4"] },
				{ fr: "vêtements", zh: "衣服", pinyin: ["yi1", "fu"] }
			]			
		},
		{
			lesson: "6",
			words: [
				{ fr: "semaine", zh: "星期", pinyin: ["xing1", "qi1"] },
				{ fr: "envisager", zh: "打算", pinyin: ["da3", "suan"] },
				{ fr: "soir", zh: "晚上", pinyin: ["wan3", "shang"] },
				{ fr: "rendez-vous", zh: "约会", pinyin: ["yue1", "hui4"] },
				{ fr: "dans", zh: "里", pinyin: ["li3"] },
				{ fr: "se reposer", zh: "休息", pinyin: ["xiu1", "xi"] },
				{ fr: "ballon", zh: "球", pinyin: ["qiu2"] },
				{ fr: "avec", zh: "跟", pinyin: ["gen1"] },
				{ fr: "ensemble", zh: "一起", pinyin: ["yi4", "qi3"] },
				{ fr: "télévision", zh: "电视", pinyin: ["dian4", "shi4"] },
				{ fr: "spécificatif<br/>(politesse)", zh: "位", pinyin: ["wei4"] },
				{ fr: "affaires", zh: "事儿", pinyin: ["shir4", ""] },
				{ fr: "café", zh: "咖啡", pinyin: ["ka1", "fei1"] },
				{ fr: "temps", zh: "时候", pinyin: ["shi2", "hou4"] },
				{ fr: "aujourd'hui", zh: "今天", pinyin: ["jin1", "tian1"] },
				{ fr: "occupé", zh: "忙", pinyin: ["mang2"] },
				{ fr: "faire", zh: "做", pinyin: ["zuo4"] },
				{ fr: "devoirs", zh: "功课", pinyin: ["gong1", "ke4"] },
				{ fr: "de rien", zh: "没关系", pinyin: ["mei2", "guan1", "xi"] },
				{ fr: "temps libre", zh: "空儿", pinyin: ["kongr4", ""] },
				{ fr: "heure", zh: "点钟", pinyin: ["dian3", "zhong1"] },
				{ fr: "demi", zh: "半", pinyin: ["ban4"] },
				{ fr: "se rencontrer", zh: "见面", pinyin: ["jian4", "mian4"] },
				{ fr: "quart d'heure", zh: "刻", pinyin: ["ke4"] },
				{ fr: "accueillir", zh: "接", pinyin: ["jie1"] },
				{ fr: "au revoir", zh: "再见", pinyin: ["zai4", "jian1"] },
				{ fr: "maintenant", zh: "现在", pinyin: ["xian4", "zai4"] },
				{ fr: "minute", zh: "分", pinyin: ["fen1"] },
				{ fr: "petit matin", zh: "早上", pinyin: ["zao3", "shang4"] },
				{ fr: "après-midi", zh: "下午", pinyin: ["xia4", "wu3"] }
			]
		},
		{
			lesson: "7",
			words: [
				{ fr: "prendre<br/>des vacances", zh: "放假", pinyin: ["fang4", "jia4"] },
				{ fr: "dernière décade<br/>d'un mois", zh: "下旬", pinyin: ["xia4", "xun2"] },
				{ fr: "après", zh: "以后", pinyin: ["yi3", "hou4"] },
				{ fr: "avant", zh: "以前", pinyin: ["yi3", "qian2"] },
				{ fr: "voyager", zh: "旅行", pinyin: ["lv3", "xing2"] },
				{ fr: "ou", zh: "或者", pinyin: ["huo4", "zhe3"] },
				{ fr: "rentrer", zh: "回", pinyin: ["hui2"] },
				{ fr: "s'inquiéter", zh: "担心", pinyin: ["dan1", "xin1"] },
				{ fr: "ne pas", zh: "别", pinyin: ["bie2"] },
				{ fr: "aider", zh: "帮助", pinyin: ["bang1", "zhu4"] },
				{ fr: "entrer", zh: "进", pinyin: ["jin4"] },
				{ fr: "chercher", zh: "找", pinyin: ["zhao3"] },
				{ fr: "porter", zh: "戴", pinyin: ["dai4"] },
				{ fr: "spécificatif<br/>(lunettes)", zh: "副", pinyin: ["fu4"] },
				{ fr: "lunettes", zh: "眼镜", pinyin: ["yan3", "jing4"] },
				{ fr: "chacun", zh: "每", pinyin: ["mei3"] },
				{ fr: "mince", zh: "瘦", pinyin: ["shou4"] },
				{ fr: "cheveux", zh: "头发", pinyin: ["tou2", "fa1"] },
				{ fr: "long", zh: "长", pinyin: ["chang2"] },
				{ fr: "habiller", zh: "穿", pinyin: ["chuan1"] },
				{ fr: "jeans", zh: "牛仔裤", pinyin: ["niu2", "zai3", "ku4"] },
				{ fr: "venir de", zh: "刚", pinyin: ["gang1"] },
				{ fr: "sortir", zh: "出", pinyin: ["chu1"] },
				{ fr: "traverser", zh: "过", pinyin: ["guo4"] },
				{ fr: "année", zh: "年", pinyin: ["nian2"] }
			]
		},
		{
			lesson: "8",
			checked: true,
			words: [
				{ fr: "près de", zh: "附近", pinyin: ["fu4", "jin4"] },
				{ fr: "banque", zh: "银行", pinyin: ["hin2", "hang2"] },
				{ fr: "de", zh: "离", pinyin: ["li2"] },
				{ fr: "loin", zh: "远", pinyin: ["yuan3"] },
				{ fr: "marcher", zh: "走", pinyin: ["zou3"] },
				{ fr: "à, vers", zh: "往", pinyin: ["wang3"] },
				{ fr: "droite", zh: "右", pinyin: ["you4"] },
				{ fr: "tourner", zh: "拐", pinyin: ["guai3"] },
				{ fr: "rue", zh: "路", pinyin: ["lu4"] },
				{ fr: "juste", zh: "就", pinyin: ["jiu4"] },
				{ fr: "bureau de poste", zh: "邮局", pinyin: ["you2", "ju2"] },
				{ fr: "à côté", zh: "旁边", pinyin: ["pang2", "bian1"] },
				{ fr: "de rien", zh: "不客气", pinyin: ["bu2", "ke4", "qi"] },
				{ fr: "centre-ville", zh: "市中心", pinyin: ["shi4", "zhong1", "xin1"] },
				{ fr: "dire", zh: "告诉", pinyin: ["gao4", "su"] },
				{ fr: "métro", zh: "地铁", pinyin: ["di4", "tie3"] },
				{ fr: "de, depuis", zh: "从", pinyin: ["cong2"] },
				{ fr: "arriver", zh: "到", pinyin: ["dao4"] },
				{ fr: "bus", zh: "公共汽车", pinyin: ["gong1", "gong4", "qi4", "che1"] },
				{ fr: "station", zh: "站", pinyin: ["zhan4"] },
				{ fr: "changer", zh: "换", pinyin: ["huan4"] },
				{ fr: "monter<br />(cheval)", zh: "骑", pinyin: ["qi2"] },
				{ fr: "vélo", zh: "自行车", pinyin: ["zi4", "xing2", "che1"] },
				{ fr: "gauche", zh: "左", pinyin: ["zuo3"] },
				{ fr: "dehors", zh: "外面", pinyin: ["wai4", "mian"] }
			]
		}
	];